#include "Heuristics.h"

#include <set>

namespace vibecheck
{
namespace
{
/** Placeholder identities that ship when nobody filled the field in. */
const juce::StringArray placeholderManufacturers {
    "yourcompany", "your company", "yourcompanyname", "mycompany", "acme", "company",
    "manufacturer", "vendor", "unknown", "example", "test", "demo", "audioplugin", "juce"
};

/** Names that come straight from a template or a first prompt. */
const juce::StringArray genericNames {
    "newproject", "audioplugin", "audiopluginexample", "myplugin", "myeffect", "testplugin",
    "simpleeq", "simplegain", "simplereverb", "basicgain", "plugin", "untitled"
};

/** Class names the JUCE templates generate and most people rename. */
const juce::StringArray templateSymbols {
    "NewProjectAudioProcessor", "AudioPluginAudioProcessor", "AudioPluginAudioProcessorEditor",
    "NewProjectAudioProcessorEditor", "MyPluginAudioProcessor", "TestPluginAudioProcessor"
};

/** Text no shipping plugin should contain. */
const juce::StringArray llmArtifacts {
    "as an ai language model", "as an ai assistant", "i cannot provide", "chatgpt", "openai",
    "gpt-4", "gpt-3", "claude ai", "copilot", "generated by ai", "ai-generated",
    "here's the implementation", "here is the implementation", "this code implements",
    "note: this is a simplified", "in a real implementation", "for demonstration purposes",
    "replace this with your", "your code here", "todo: implement", "implement me",
    "lorem ipsum", "placeholder implementation"
};

/** Paths and filenames that only exist because an AI coding tool was used on the project. A build
    path is baked into a binary by assertions and debug info, so a project that lived inside one of
    these folders announces it. */
const juce::StringArray aiToolMarkers {
    "/.claude", "claude-code", "claude.md", "agents.md", "/.cursor", ".cursorrules", "/.codex", "/.gemini",
    "/.aider", ".aider.chat", "/.windsurf", "copilot-instructions", "/.continue/", "/.kiro"
};

/** Four-character AudioUnit codes that ship in the JUCE templates and examples. */
const juce::StringArray defaultManufacturerCodes { "Manu", "Juce", "Test", "Plug", "Demo", "Acme" };
const juce::StringArray defaultPluginCodes { "Dem0", "Plug", "Test", "Aap1", "Demo", "Plg1", "Dmo1" };

/** Libm calls that have no business on an audio thread in a tight loop. */
const juce::StringArray scalarMathSymbols { "_sin", "_cos", "_tan", "_exp", "_pow", "_log", "_log10", "_atan2" };


/** The text of the first <string> that follows a given <key> in a plist. */
juce::String plistValueAfterKey (const juce::String& plist, const juce::String& key)
{
    const auto keyAt = plist.indexOf ("<key>" + key + "</key>");

    if (keyAt < 0)
        return {};

    const auto open = plist.indexOf (keyAt, "<string>");
    const auto close = plist.indexOf (keyAt, "</string>");

    if (open < 0 || close < open)
        return {};

    return plist.substring (open + 8, close).trim();
}

/** The names a plugin's own code lives in, read from Itanium-mangled symbols: the first name
    inside the mangling is the class or namespace. Framework scopes are left out, so what remains
    is what the author (or generator) named. */
juce::StringArray userScopes (const juce::StringArray& symbols)
{
    static const juce::StringArray framework { "juce", "Steinberg", "VST3", "Vst", "Presonus", "VSTGUI", "std", "__cxxabiv1",
                                                "__gnu_cxx", "choc", "clap", "farbot", "moodycamel" };
    juce::StringArray scopes;
    std::set<juce::String> seen;

    for (const auto& symbol : symbols)
    {
        if (! symbol.startsWith ("__ZN"))
            continue;

        auto position = 4;

        while (position < symbol.length() && (symbol[position] == 'r' || symbol[position] == 'V' || symbol[position] == 'K'))
            ++position;

        int length = 0, digits = 0;

        while (position + digits < symbol.length() && juce::CharacterFunctions::isDigit (symbol[position + digits]) && digits < 3)
            length = length * 10 + (symbol[position + digits++] - '0');

        if (digits == 0 || length <= 0 || position + digits + length > symbol.length())
            continue;

        const auto name = symbol.substring (position + digits, position + digits + length);

        if (! framework.contains (name) && seen.insert (name).second)
            scopes.add (name);
    }

    return scopes;
}

/** Domains that appear in a binary because of the frameworks inside it, not the author. */
bool isFrameworkDomain (const juce::String& url)
{
    for (const auto* domain : { "juce.com", "steinberg", "apple.com", "w3.org", "github.com/juce", "github.com/steinberg",
                                 "gnu.org", "unicode.org", "mozilla", "boost.org", "llvm.org", "openssl", "curl.se", "sqlite.org",
                                 "zlib", "libpng", "ietf.org", "creativecommons", "xiph.org", "xmlsoft", "freetype", "ogg", "flac",
                                 "mp3", "schemas.", "ns.adobe", "purl.org", "example.com", "localhost", "127.0.0.1", "xml.org",
                                 "docs.microsoft", "msdn", "khronos.org", "opengl", "python.org", "gcc.gnu", "isocpp" })
        if (url.containsIgnoreCase (domain))
            return true;

    return false;
}

bool anyContains (const juce::StringArray& haystack, const juce::String& needle)
{
    for (const auto& entry : haystack)
        if (entry.contains (needle))
            return true;

    return false;
}

bool anyEquals (const juce::StringArray& haystack, const juce::String& needle)
{
    for (const auto& entry : haystack)
        if (entry == needle)
            return true;

    return false;
}

juce::String firstMatch (const juce::StringArray& haystack, const juce::StringArray& needlesLowerCase)
{
    for (const auto& entry : haystack)
    {
        const auto lower = entry.toLowerCase();

        for (const auto& needle : needlesLowerCase)
            if (lower.contains (needle))
                return entry.substring (0, 120);
    }

    return {};
}
} // namespace

juce::String toString (Family family)
{
    switch (family)
    {
        case Family::metadata:       return "metadata";
        case Family::boilerplate:    return "boilerplate";
        case Family::dspNaivety:     return "DSP";
        case Family::stringArtifact: return "strings";
        case Family::behaviour:      return "behaviour";
        case Family::source:         return "source";
    }

    return "other";
}

VibeReport assessVibe (const BinaryFacts& facts, const juce::PluginDescription& description, const BehaviourReport* behaviour,
                       const SourceReport* source)
{
    VibeReport report;
    report.opacityReason = facts.opacityReason();

    // How much of the binary could be read at all. Everything below is weighed against this.
    if (facts.ok)
    {
        // Where binaries carry no symbol table as a matter of course (Windows), the symbols are not
        // missing evidence, so the strings alone decide how much could be read.
        const auto symbolFactor = facts.symbolTableExpected ? juce::jmin (1.0, (double) facts.definedSymbols.size() / 500.0)
                                                            : juce::jmin (1.0, (double) facts.strings.size() / 1500.0);
        const auto stringFactor = juce::jmin (1.0, (double) facts.strings.size() / 2000.0);
        report.confidence = 0.15 + 0.50 * symbolFactor + 0.35 * stringFactor;

        if (facts.paceWrapped)
            report.confidence = 0.05;
        else if (facts.stripped)
            report.confidence *= 0.5;
    }

    const auto add = [&report] (Family family, juce::String finding, juce::String detail, juce::String explanation, double points)
    {
        report.evidence.push_back ({ family, std::move (finding), std::move (detail), std::move (explanation), points });
        report.score += points;
    };

    // --- Metadata: identity nobody filled in -------------------------------------------------
    const auto manufacturer = description.manufacturerName.toLowerCase().trim();

    // Whole words only: "Contest Audio" is not a placeholder just because it contains "test".
    juce::StringArray manufacturerWords;
    manufacturerWords.addTokens (manufacturer, " -_.,", "");
    manufacturerWords.removeEmptyStrings();

    if (manufacturer.isEmpty())
        add (Family::metadata, "no manufacturer name at all", "(empty)", "Commercial or properly branded plugins usually set a manufacturer name. AI generators often leave it blank.", 18.0);
    else if (placeholderManufacturers.contains (manufacturer, true) || std::any_of (manufacturerWords.begin(), manufacturerWords.end(),
                 [] (const juce::String& word) { return placeholderManufacturers.contains (word, true); }))
        add (Family::metadata, "placeholder manufacturer name", description.manufacturerName, "A placeholder like 'yourcompany' is a strong indicator of an unmodified generated template.", 18.0);

    if (genericNames.contains (description.name.toLowerCase().removeCharacters (" "), true))
        add (Family::metadata, "template-default plugin name", description.name, "Using a generic default name for the plugin project often means the developer skipped setup steps.", 12.0);

    if (description.version.isEmpty() || description.version == "1.0.0" || description.version == "1.0")
        add (Family::metadata, "untouched default version string", description.version.isEmpty() ? "(empty)" : description.version, "A default version string, which generated projects rarely move beyond and many first releases share.", 3.0);

    if (facts.infoPlist.containsIgnoreCase ("com.yourcompany")
        || facts.infoPlist.containsIgnoreCase ("com.example")
        || facts.infoPlist.containsIgnoreCase ("com.mycompany"))
        add (Family::metadata, "placeholder bundle identifier", "com.yourcompany / com.example", "macOS plugins use reverse-DNS bundle IDs. Unchanged placeholders indicate a raw generated template.", 20.0);

    // The four-letter codes an AudioUnit is registered under. Templates ship with fixed ones, and a
    // plugin that kept them has never had its identity set up.
    {
        const auto manufacturerCode = plistValueAfterKey (facts.infoPlist, "manufacturer");
        const auto pluginCode = plistValueAfterKey (facts.infoPlist, "subtype");
        const auto manufacturerIsDefault = manufacturerCode.isNotEmpty() && defaultManufacturerCodes.contains (manufacturerCode, false);
        const auto pluginIsDefault = pluginCode.isNotEmpty() && defaultPluginCodes.contains (pluginCode, false);

        if (manufacturerIsDefault && pluginIsDefault)
            add (Family::metadata, "AudioUnit codes left at the template defaults", manufacturerCode + " / " + pluginCode,
                 "JUCE's templates register every plugin as the same manufacturer and plugin codes. Keeping both means the project identity was never filled in.", 14.0);
        else if (manufacturerIsDefault || pluginIsDefault)
            add (Family::metadata, "an AudioUnit code left at the template default", manufacturerIsDefault ? manufacturerCode : pluginCode,
                 "One of the four-letter registration codes is still the one the JUCE template ships with.", 7.0);
    }

    // Placeholder author text in the bundle's own metadata.
    for (const auto* marker : { "your name", "your company", "john doe", "jane doe", "author name", "company name", "lorem ipsum" })
        if (facts.infoPlist.containsIgnoreCase (marker))
        {
            add (Family::metadata, "placeholder author or copyright text", marker,
                 "The bundle's copyright or author field still holds filler text from a template.", 10.0);
            break;
        }

    // A VST3 can describe its vendor in moduleinfo.json. A plugin that fills in neither a website nor
    // an email gives nobody a way to reach the maker.
    if (facts.moduleInfo.isNotEmpty())
    {
        const auto info = juce::JSON::parse (facts.moduleInfo);
        const auto factory = info.getProperty ("Factory Info", {});
        const auto url = factory.getProperty ("URL", {}).toString().trim();
        const auto email = factory.getProperty ("E-Mail", {}).toString().trim();

        if (factory.isObject() && url.isEmpty() && email.isEmpty())
            add (Family::metadata, "VST3 lists no website and no email", "moduleinfo.json",
                 "Shipping plugins nearly always say how to reach the vendor. Generated projects rarely fill this in.", 6.0);
    }

    // No developer account behind the signature: weak, since hobbyists share it, but it is part of
    // the picture of something nobody set up to be distributed.
    if (facts.hasSignature && facts.adHocSigned && ! facts.paceWrapped && facts.teamIdentifier.isEmpty())
        add (Family::metadata, "ad hoc code signature", facts.signingIdentifier.isNotEmpty() ? facts.signingIdentifier : "ad hoc",
             "Signed without an Apple developer identity, the default for a build nobody has prepared for release.", 3.0);

    // --- Boilerplate: template scaffolding left in place --------------------------------------
    for (const auto& symbol : templateSymbols)
        if (anyContains (facts.definedSymbols, symbol) || anyContains (facts.strings, symbol))
        {
            add (Family::boilerplate, "untouched JUCE template class name", symbol, "JUCE creates standard classes like 'NewProjectAudioProcessor'. Leaving these unmodified suggests code was generated and compiled without manual structuring.", 22.0);
            break;
        }

    // There is deliberately no check for GenericAudioProcessorEditor here. The name appears in
    // every JUCE binary whether or not the plugin instantiates it, so it detects the framework
    // rather than the author's choice - it marked a hand-written fixture with a custom editor.

    // The default file names, matched whole. A file called SonobusPluginEditor.cpp is somebody's own
    // naming; PluginEditor.cpp is what the template hands out. Many careful people keep those names
    // too, so this is weak.
    {
        juce::String templateFile;

        for (const auto& line : facts.strings)
        {
            if (! line.endsWithIgnoreCase (".cpp") || line.length() > 200)
                continue;

            // Static initialisers appear as __GLOBAL__sub_I_<file>, and asserts carry full paths.
            auto name = line.fromLastOccurrenceOf ("/", false, false);
            name = name.fromLastOccurrenceOf ("_I_", false, false);

            if (name.equalsIgnoreCase ("PluginProcessor.cpp") || name.equalsIgnoreCase ("PluginEditor.cpp"))
            {
                templateFile = line.substring (0, 120);
                break;
            }
        }

        if (templateFile.isNotEmpty())
            add (Family::boilerplate, "default template source file names in the binary", templateFile,
                 "A generated project keeps the file names the template gave it. Careful developers sometimes do too, so it counts for more alongside other leftovers than on its own.", 8.0);
    }

    // Class names read from the symbol table. The names a JUCE project starts with, and the ones
    // most generated projects use for the processor and editor pair.
    {
        const auto scopes = userScopes (facts.definedSymbols);

        if (scopes.contains ("PluginProcessor") || scopes.contains ("PluginEditor"))
            add (Family::boilerplate, "generic class names for the processor and editor",
                 scopes.contains ("PluginProcessor") ? "PluginProcessor" : "PluginEditor",
                 "Projects started from a prompt or a stock template tend to keep these names. A plugin with its own identity usually names its classes after what they are.", 6.0);
    }

    // --- Boilerplate: AI-generated parameter setups -------------------------------------------
    // AI code generators overwhelmingly use ALL_CAPS parameter IDs. We look for two signals:
    //   1. ALL CAPS ID paired with a matching title-case label (strongest signal)
    //   2. Standalone ALL CAPS IDs that look like audio parameter names (still a clear signal)
    int allCapsParamPairs = 0;
    int allCapsStandaloneIds = 0;
    juce::StringArray foundPairs;
    juce::StringArray standaloneIds;

    // Common audio parameter ID keywords that AI generators use
    const juce::StringArray paramKeywords {
        "GAIN", "DRIVE", "MIX", "OUTPUT", "INPUT", "LEVEL", "VOLUME", "PAN",
        "FREQ", "ATTACK", "RELEASE", "RATIO", "THRESHOLD", "MAKEUP", "POWER",
        "STYLE", "TYPE", "MODE", "SPEED", "DEPTH", "FEEDBACK", "DELAY", "TIME",
        "DECAY", "SIZE", "ROOM", "DAMPING", "WIDTH", "TONE", "CUTOFF", "RESONANCE",
        "RATE", "AMOUNT", "MONO", "SWAP", "BYPASS", "WET", "DRY"
    };

    // Framework/OS strings that happen to be ALL CAPS with a title-case match — NOT param IDs
    const juce::StringArray frameworkExclusions {
        "OPEN", "CLOSE", "SAVE", "LOAD", "FILE", "EDIT", "VIEW", "HELP", "QUIT",
        "MIDI", "AUDIO", "NONE", "TRUE", "FALSE", "LEFT", "RIGHT", "MONO", "STEREO",
        "VST3", "CLAP", "JUCE", "INFO", "WARN", "ERROR", "DEBUG", "NULL",
        "RNK3", "UTF8", "RGBA", "ARGB", "INIT", "EXIT", "DATA", "TEXT", "NAME"
    };

    for (const auto& str1 : facts.strings)
    {
        if (str1.length() >= 3 && str1.length() <= 20 && str1 == str1.toUpperCase() 
            && str1.containsOnly("ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789_")
            && str1[0] >= 'A' && str1[0] <= 'Z'
            && str1.substring(0, str1.length()).containsOnly("ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789_"))
        {
            // Skip strings that don't have at least 2 consecutive uppercase letters
            // This filters out hex codes like C9H7 and framework constants like VST3
            bool hasTwoConsecutiveAlpha = false;
            for (int i = 0; i < str1.length() - 1; ++i)
                if (str1[i] >= 'A' && str1[i] <= 'Z' && str1[i+1] >= 'A' && str1[i+1] <= 'Z')
                { hasTwoConsecutiveAlpha = true; break; }
            if (! hasTwoConsecutiveAlpha) continue;

            // Skip known framework/OS strings
            if (frameworkExclusions.contains (str1, true)) continue;

            // Only names that read as audio parameters count. An ALL CAPS string next to a
            // title-case twin is not enough on its own: a plugin called "Sway" has "Sway" and
            // "SWAY" in its strings whatever its author did.
            auto base = str1;
            while (base.isNotEmpty() && base[base.length() - 1] >= '0' && base[base.length() - 1] <= '9')
                base = base.dropLastCharacters (1);

            if (! paramKeywords.contains (base, true))
                continue;

            // A matching title-case label is the stronger form of the pattern.
            const auto titleCase = str1.substring (0, 1) + str1.substring (1).toLowerCase();
            const auto hasPair = anyEquals (facts.strings, titleCase);

            if (hasPair && ! foundPairs.contains (str1))
            {
                allCapsParamPairs++;
                foundPairs.add (str1);
            }
            else if (! hasPair && ! standaloneIds.contains (str1))
            {
                allCapsStandaloneIds++;
                standaloneIds.add (str1);
            }
        }
    }

    if (allCapsParamPairs >= 2)
        add (Family::boilerplate, "AI-style ALL CAPS parameter IDs paired with labels", foundPairs.joinIntoString (", "), "AI tools frequently hallucinate parameter IDs entirely in uppercase (e.g. CUTOFF instead of cutoff_hz), which is a non-standard convention.", 40.0);
    else if (allCapsParamPairs == 1 && allCapsStandaloneIds >= 1)
    {
        auto combined = foundPairs;
        combined.addArray (standaloneIds);
        add (Family::boilerplate, "AI-style ALL CAPS parameter IDs", combined.joinIntoString (", "), "AI tools frequently hallucinate parameter IDs entirely in uppercase, which is a non-standard convention.", 35.0);
    }
    else if (allCapsStandaloneIds >= 2)
        add (Family::boilerplate, "ALL CAPS strings matching common audio parameter names", standaloneIds.joinIntoString (", "), "AI tools frequently use uppercase parameter names internally.", 18.0);
    // One lone uppercase string is deliberately not scored: JUCE, UI code and the UAD, SonoBus and
    // Apple binaries all carry strings like RATE or INPUT, so it fired on hand-written plugins as
    // often as on generated ones.

    const auto hasCreateParameterLayout = anyContains (facts.definedSymbols, "createParameterLayout") || anyContains (facts.strings, "createParameterLayout");
    const auto hasParametersString = anyContains (facts.strings, "Parameters");
    if (hasCreateParameterLayout && hasParametersString)
        add (Family::boilerplate, "default AudioProcessorValueTreeState scaffolding", "createParameterLayout() + \"Parameters\"", "This is the JUCE tutorial's own parameter setup, copied verbatim by people and models alike. It says the project began from a tutorial, not who wrote the rest.", 8.0);

    if (anyContains (facts.definedSymbols, "getRawParameterValue") || anyContains (facts.strings, "getRawParameterValue"))
        add (Family::dspNaivety, "getRawParameterValue() is in the binary", "getRawParameterValue", "Weak evidence. Generated code often polls parameters straight from the audio loop, but so does a great deal of tutorial-derived human code, and the call can be in JUCE itself.", 4.0);

    // CriticalSection is part of JUCE and sits in every JUCE binary, so only a bare std::mutex
    // tells us anything, and only when JUCE is not also in the binary to explain it.
    const auto usesJuceFramework = anyContains (facts.strings, "juce::") || anyContains (facts.strings, "JucePlugin")
                                   || anyContains (facts.definedSymbols, "juce") || anyContains (facts.undefinedSymbols, "juce");

    if (! usesJuceFramework && (anyContains (facts.undefinedSymbols, "mutex::lock") || anyContains (facts.definedSymbols, "mutex::lock")))
        add (Family::dspNaivety, "std::mutex locking in a plugin with no framework to explain it", "std::mutex::lock",
             "Models often fix thread safety with a lock inside the audio callback, which can cause dropouts. Weak on its own.", 8.0);

    // There is deliberately no check for getStateInformation or the program-management overrides.
    // JUCE declares them pure virtual, so every plugin defines them whether or not the bodies are
    // empty, and a symbol table cannot show a body. The previous version scored them and marked a
    // hand-written fixture as machine-made.

    // --- Boilerplate: BinaryData::bg_jpg background image ------------------------------------
    // AI generators consistently embed a single background image as bg_jpg in BinaryData.
    if (anyEquals (facts.strings, "bg_jpg") || anyContains (facts.definedSymbols, "bg_jpg"))
        add (Family::boilerplate, "BinaryData::bg_jpg background image (common AI generator pattern)", "bg_jpg", "AI generators frequently hallucinate embedding a background image named 'bg.jpg' into the UI.", 15.0);
    else
        for (const auto* name : { "background_jpg", "background_png", "bg_png", "background_jpeg", "bg_jpeg" })
            if (anyEquals (facts.strings, name) || anyContains (facts.definedSymbols, name))
            {
                add (Family::boilerplate, "a generic embedded background image", name,
                     "A single image called background or bg is the most common asset in a generated plugin UI, and in plenty of hand-made ones.", 3.0);
                break;
            }

    // --- Boilerplate: timer-driven repaint metering ------------------------------------------
    // AI plugin editors invariably use Timer::startTimerHz + timerCallback => repaint() to
    // display crude metering. The variable names (rmsLevel etc.) don't survive in binaries,
    // but the editor's own timerCallback symbol does.
    {
        bool hasPluginTimerCallback = false;
        for (const auto& sym : facts.definedSymbols)
        {
            if (sym.contains ("timerCallback") && sym.contains ("Editor")
                && ! sym.contains ("juce") && ! sym.contains ("Steinberg"))
            {
                hasPluginTimerCallback = true;
                break;
            }
        }
        if (hasPluginTimerCallback)
            add (Family::boilerplate, "editor uses Timer for repaint polling (common AI metering pattern)",
                 "Editor::timerCallback", "Generated editors often poll and repaint on a timer. So do many hand-written meters, so this carries little weight on its own.", 3.0);
    }

    // --- DSP: audio code written without regard for the audio thread --------------------------
    const auto usesAccelerate = anyContains (facts.linkedLibraries, "Accelerate")
                                || anyContains (facts.undefinedSymbols, "vDSP_")
                                || anyContains (facts.definedSymbols, "vDSP_");

    // JUCE links Accelerate and calls scalar maths on its own account, so in a JUCE plugin
    // neither fact says anything about the author.
    const auto usesJuce = anyContains (facts.strings, "juce::")
                          || anyContains (facts.strings, "JucePlugin")
                          || anyContains (facts.definedSymbols, "juce")
                          || anyContains (facts.undefinedSymbols, "juce");

    juce::StringArray scalarCalls;

    for (const auto& symbol : scalarMathSymbols)
        if (anyEquals (facts.undefinedSymbols, symbol))
            scalarCalls.add (symbol.substring (1));

    if (usesJuce)
    {
        report.notEvaluated.add ("DSP: this is a JUCE plugin, and JUCE links Accelerate and calls "
                                 "scalar maths itself, so the author's own choices cannot be told "
                                 "apart from the framework's");
    }
    else if (facts.platform == "Windows")
    {
        // Windows has no Accelerate, so the absence of a vectorised path is not a choice the
        // author made, and the check would flag every plugin that calls sin().
        report.notEvaluated.add ("DSP: the scalar-maths check is only meaningful on macOS, where "
                                 "Accelerate is the easy vectorised alternative");
    }
    else if (! scalarCalls.isEmpty() && ! usesAccelerate)
    {
        add (Family::dspNaivety, "scalar libm maths with no vectorised path anywhere",
             scalarCalls.joinIntoString (", "), "Most modern handwritten plugins use vectorised maths for performance. AI code is typically naive and relies solely on scalar standard library maths functions.", 12.0);
    }
    else if (! usesAccelerate)
    {
        // Deliberately not scored. Plenty of perfectly good plugins have no need to vectorise
        // anything, so the mere absence of SIMD is not evidence of anything at all. Only the
        // positive finding above counts.
        report.notEvaluated.add ("DSP: nothing vectorised was found, which on its own says nothing "
                                 "- a simple effect has no need of it");
    }

    // --- Strings: text nobody meant to ship ---------------------------------------------------
    // A build path that runs through an AI tool's own folder, or names its instruction file.
    if (const auto marker = firstMatch (facts.strings, aiToolMarkers); marker.isNotEmpty())
        add (Family::stringArtifact, "a build path that names an AI coding tool", marker,
             "Assertions and debug info bake the source path into the binary. This one passes through a folder or file that only exists when an AI coding assistant is working on the project.", 30.0);

    const auto artifact = firstMatch (facts.strings, llmArtifacts);

    if (artifact.isNotEmpty())
        add (Family::stringArtifact, "text that reads like it came from a chat assistant", artifact, "The binary contains strings like 'Here is the C++ code', which is an unmistakable tell of AI chat output pasted directly into the source.", 30.0);

    // --- Signals pointing the other way -------------------------------------------------------
    if (usesAccelerate && ! usesJuce)
        report.humanSignals.add ("uses vectorised DSP (Accelerate or vDSP), which is a deliberate optimisation");

    if (description.manufacturerName.isNotEmpty() && report.evidence.empty())
        report.humanSignals.add ("identity fields are filled in properly");

    if (facts.definedSymbols.size() > 2000 && ! usesJuce)
        report.humanSignals.add ("large, varied symbol table: " + juce::String (facts.definedSymbols.size()) + " exported symbols");

    if (facts.platform == "Windows" && facts.hasSignature)
        report.humanSignals.add ("carries an Authenticode signature, which needs a code-signing certificate that costs money");

    if (facts.teamIdentifier.isNotEmpty())
        report.humanSignals.add ("signed by an Apple developer team (" + facts.teamIdentifier + "), which needs an account and a fee");

    // The author's own web address, which a prompted plugin rarely carries.
    for (const auto& line : facts.strings)
    {
        const auto at = line.indexOf ("https://");

        if (at < 0 || line.length() > 200)
            continue;

        const auto url = line.substring (at).upToFirstOccurrenceOf (" ", false, false);

        if (url.length() > 14 && ! isFrameworkDomain (url))
        {
            report.humanSignals.add ("contains a web address that is not a framework's: " + url.substring (0, 70));
            break;
        }
    }

    {
        int licensing = 0;

        for (const auto* word : { "license key", "serial number", "activation", "activate", "trial", "authoriz", "check for update", "machine id" })
            if (firstMatch (facts.strings, { word }).isNotEmpty())
                ++licensing;

        if (licensing >= 2)
            report.humanSignals.add ("has licensing or update machinery, which belongs to a product that ships");
    }

    if (facts.paceWrapped)
        report.humanSignals.add ("wrapped for commercial copy protection, which hobbyist projects do not do");

    if (facts.stripped && ! facts.paceWrapped)
        report.notEvaluated.add ("boilerplate: the binary is stripped, so class names could only be "
                                 "looked for in strings, not in the symbol table");

    // --- iPlug2: the framework's example controls, used as shipped ----------------------------
    // IVColorSwatchControl, IVMenuButtonControl and IVSlideSwitchControl are the vector widgets the
    // iPlug2 example projects are built from. A plugin whose own interface is made of them has kept
    // the starter UI.
    {
        int stockControls = 0;

        for (const auto* control : { "IVColorSwatchControl", "IVMenuButtonControl", "IVSlideSwitchControl", "IVTabSwitchControl", "IVMultiSliderControl" })
            if (anyContains (facts.definedSymbols, control) || anyContains (facts.strings, control))
                ++stockControls;

        if (stockControls >= 2)
            add (Family::boilerplate, "iPlug2's example controls kept as the interface", juce::String (stockControls) + " stock controls",
                 "The iPlug2 example projects are built from these vector widgets. Shipping them unchanged says the UI is the starter one. Plenty of capable plugins start there, so this is moderate.", 8.0);
    }

    // --- Several tutorial leftovers together --------------------------------------------------
    // One of these is common in careful work. Four of them together is a project that never left
    // the tutorial, and that is how most generated plugins look.
    {
        int leftovers = 0;

        for (const auto& item : report.evidence)
            if (item.finding.startsWith ("default template source file names")
                || item.finding.startsWith ("default AudioProcessorValueTreeState")
                || item.finding.startsWith ("getRawParameterValue")
                || item.finding.startsWith ("editor uses Timer")
                || item.finding.startsWith ("untouched default version")
                || item.finding.startsWith ("a generic embedded background"))
                ++leftovers;

        if (leftovers >= 4)
            add (Family::boilerplate, "four or more tutorial leftovers together", juce::String (leftovers) + " of 6 checked",
                 "Each of these is common alone. Together they describe a project that never moved past the tutorial it began from, which is the usual shape of a generated plugin.", 20.0);
        else if (leftovers == 3)
            add (Family::boilerplate, "three tutorial leftovers together", "3 of 6 checked",
                 "Each of these is common alone. Three together point at a project still wearing most of its starter scaffolding.", 12.0);
    }

    // --- Behaviour: what the audio thread does ------------------------------------------------
    if (behaviour != nullptr && behaviour->ok)
    {
        if (behaviour->allocationsMeasured)
        {
            if (behaviour->fractionOfBlocksAllocating >= 0.5)
                add (Family::behaviour, "allocates memory on the audio thread in most blocks",
                     juce::String (behaviour->allocationsPerBlock, 1) + " per block, " + juce::String (juce::roundToInt (behaviour->fractionOfBlocksAllocating * 100.0)) + "% of blocks",
                     "Real-time audio code must not ask the allocator for memory, because it can stall. Generated code often builds vectors and strings inside processBlock without a thought for that.", 25.0);
            else if (behaviour->allocationsPerBlockAutomated >= 5.0)
                add (Family::behaviour, "allocates heavily on the audio thread when parameters move",
                     juce::String (behaviour->allocationsPerBlockAutomated, 1) + " per block with automation",
                     "Steady audio costs nothing, but moving a parameter makes the plugin rebuild things from the heap on the audio thread. Easy to miss, and typical of code that was never profiled.", 15.0);
            else if (behaviour->allocationsPerBlock >= 0.5)
                add (Family::behaviour, "occasional allocation on the audio thread", juce::String (behaviour->allocationsPerBlock, 2) + " per block",
                     "A few allocations on the audio thread. Careful plugins avoid this entirely, but some mature ones do it too.", 6.0);
        }

        if (behaviour->cpuPercent >= 10.0)
            add (Family::behaviour, "unusually expensive for what it does", juce::String (behaviour->cpuPercent, 1) + "% of a core at 48 kHz / 512",
                 "Most effects cost well under 3% of a core. Naive per-sample maths, coefficient rebuilds and unnecessary precision push code far above that. Oversampling or convolution can legitimately do the same, so this is moderate.", 12.0);
        else if (behaviour->cpuPercent >= 5.0)
            add (Family::behaviour, "expensive for what it does", juce::String (behaviour->cpuPercent, 1) + "% of a core at 48 kHz / 512",
                 "Higher than most effects of this kind.", 6.0);

        if (behaviour->spikeRatio >= 5.0)
            add (Family::behaviour, "erratic block times", "slowest 1% of blocks take " + juce::String (behaviour->spikeRatio, 1) + "x the median",
                 "Occasional very slow blocks usually mean locks, allocation or file access during processing.", 5.0);

        if (! behaviour->instrument && behaviour->smallBufferOverhead >= 15.0)
            add (Family::behaviour, "heavy fixed work every block", juce::String (behaviour->smallBufferOverhead, 0) + "x the cost per sample at 16-sample blocks",
                 "Work done once per block, such as rebuilding filters or reading every parameter, costs far more per sample as buffers shrink. Weak: block-based algorithms such as FFT processors do this legitimately.", 4.0);

        if (behaviour->denormalSlowdown >= 5.0)
            add (Family::behaviour, "slows down badly on near-silent input", juce::String (behaviour->denormalSlowdown, 1) + "x slower",
                 "A plugin that does not guard against denormal numbers can spike the CPU in quiet passages.", 6.0);
        else if (behaviour->allocationsMeasured && behaviour->allocationsPerBlock < 0.01 && behaviour->worstAllocationsInOneBlock == 0)
            report.humanSignals.add ("makes no allocations on the audio thread, which takes deliberate work");
    }
    else if (behaviour == nullptr)
    {
        report.notEvaluated.add ("behaviour: the plugin has not been run. Use Deep check to measure what its audio thread does.");
    }

    // --- Source: what the code and its repository show ----------------------------------------
    const auto sourceRead = source != nullptr && source->ok;

    if (sourceRead)
    {
        for (const auto& finding : source->findings)
            add (Family::source, finding.finding, finding.detail, finding.explanation, finding.points);

        if (source->findings.empty())
            report.humanSignals.add ("its source code was read (" + source->origin + ") and nothing was found in it");
    }
    else if (source == nullptr)
    {
        report.notEvaluated.add ("source: not read. If the plugin's code is public, Source check reads it and its commit history.");
    }

    report.score = juce::jlimit (0.0, 100.0, report.score);

    // Readable source is evidence in its own right, even where the binary is encrypted.
    report.conclusive = (facts.readable() && report.confidence >= 0.35) || sourceRead;

    if (! report.conclusive)
    {
        report.headline = "Insufficient evidence";

        if (report.opacityReason.isEmpty())
            report.opacityReason = "too little of the binary could be read to judge it either way";
    }
    else if (report.score < 10.0)
        report.headline = "Looks hand-written";
    else if (report.score < 30.0)
        report.headline = "Some template smell";
    else if (report.score < 55.0)
        report.headline = "Substantial AI fingerprints";
    else
        report.headline = "Reads as machine-generated";

    return report;
}

juce::String VibeReport::summary() const
{
    juce::String text;
    text << headline;

    if (conclusive)
        text << ": " << juce::String (score, 0) << "% (confidence " << juce::String (confidence * 100.0, 0) << "%)";
    else
        text << " - " << opacityReason;

    if (! evidence.empty())
    {
        text << "\n\nfingerprints found:";

        for (const auto& item : evidence)
            text << "\n  [" << toString (item.family) << "] " << item.finding
                 << "  (+" << juce::String (item.points, 0) << ")"
                 << "\n      " << item.detail;
    }
    else if (conclusive)
    {
        text << "\n\nno fingerprints found.";
    }

    if (! humanSignals.isEmpty())
    {
        text << "\n\npointing the other way:";

        for (const auto& signal : humanSignals)
            text << "\n  " << signal;
    }

    if (! notEvaluated.isEmpty())
    {
        text << "\n\ncould not be judged:";

        for (const auto& note : notEvaluated)
            text << "\n  " << note;
    }

    text << "\n\nThis measures template and boilerplate smells, not authorship. A careful human "
            "using a template scores high; a model that was told to write idiomatic, optimised "
            "code scores low.";

    return text;
}
} // namespace vibecheck
